# Generated by Django 4.2.7 on 2026-05-06 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fashion/')),
                ('event_type', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('wedding', 'Wedding'), ('party', 'Party'), ('business', 'Business'), ('outdoor', 'Outdoor'), ('sports', 'Sports')], max_length=20)),
                ('body_type', models.CharField(blank=True, max_length=30)),
                ('skin_tone', models.CharField(blank=True, max_length=30)),
                ('suggestions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
