# Generated by Django 4.2.7 on 2026-01-01 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('skin_type', models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20, null=True)),
                ('hair_type', models.CharField(blank=True, choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pregnant', models.BooleanField(default=False, help_text='Currently pregnant')),
                ('has_cardio_issues', models.BooleanField(default=False, help_text='Cardiovascular/heart issues')),
                ('is_diabetic', models.BooleanField(default=False, help_text='Diabetes')),
                ('has_allergies', models.BooleanField(default=False, help_text='Allergies to medications/products')),
                ('has_hypertension', models.BooleanField(default=False, help_text='High blood pressure')),
                ('has_asthma', models.BooleanField(default=False, help_text='Asthma')),
                ('has_skin_conditions', models.BooleanField(default=False, help_text='Existing skin conditions')),
                ('has_scalp_conditions', models.BooleanField(default=False, help_text='Existing scalp conditions')),
                ('other_conditions', models.TextField(blank=True, help_text='Other medical conditions or notes', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('known_allergens', models.TextField(blank=True, help_text='Known allergens (if any)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
