# Generated by Django 4.2.7 on 2026-05-06 12:44

import core.encryption.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='current_medications',
            field=core.encryption.fields.EncryptedTextField(blank=True, help_text='Current medications', null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='known_allergens',
            field=core.encryption.fields.EncryptedTextField(blank=True, help_text='Known allergens (if any)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='other_conditions',
            field=core.encryption.fields.EncryptedTextField(blank=True, help_text='Other medical conditions or notes', null=True),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('dermatologist', 'Dermatologist'), ('salon', 'Salon')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
