# Generated by Django 4.2.7 on 2026-04-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('analysis_type', models.CharField(choices=[('skin', 'Skin'), ('scalp', 'Scalp')], max_length=10)),
                ('original_image', models.CharField(blank=True, default='', max_length=500)),
                ('face_url', models.CharField(blank=True, max_length=500, null=True)),
                ('scalp_url', models.CharField(blank=True, max_length=500, null=True)),
                ('segmentation_mask', models.CharField(blank=True, max_length=500, null=True)),
                ('visualized_image', models.CharField(blank=True, max_length=500, null=True)),
                ('yolo_visualization', models.CharField(blank=True, max_length=500, null=True)),
                ('yolo_chart', models.CharField(blank=True, max_length=500, null=True)),
                ('efficientnet_visualization', models.CharField(blank=True, max_length=500, null=True)),
                ('conditions', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('recommendations_structured', models.JSONField(default=dict)),
                ('max_severity', models.IntegerField(default=0)),
                ('severity_label', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Mild', max_length=20)),
                ('recommend_dermatologist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
