import { CheckSquare } from 'lucide-react';
import StaticPage from '../components/StaticPage';

export default function Consent() {
  return (
    <StaticPage
      title="Consent Form"
      subtitle="Last updated: 19 June 2026"
      icon={<CheckSquare size={20} />}
    >
      <h2>Informed Consent to AI Image Analysis</h2>
      <p>
        Before using ME's skin or scalp analysis, please read and agree to the
        following. By checking the consent box at sign-up and by uploading an image,
        you confirm that you understand and accept these terms.
      </p>

      <h2>1. What you are consenting to</h2>
      <ul>
        <li>You consent to ME processing the face, scalp, or body images you upload using automated AI models (face/scalp detection, condition classification, and severity estimation).</li>
        <li>You consent to your stated health profile (e.g. allergies, pregnancy, diabetes, current medications) being used to personalise and safety-filter your recommendations.</li>
        <li>You consent to your analysis results being stored in your account history so you can review them later.</li>
      </ul>

      <h2>2. How your image is handled</h2>
      <ul>
        <li>Images are processed to produce condition scores and visual overlays used to generate your report.</li>
        <li>Recommendation text is generated by a large language model provider; your raw image is not used to train third-party models.</li>
        <li>Your images and results are never sold or shared with advertisers, insurers, or unrelated third parties.</li>
      </ul>

      <h2>3. This is not a medical diagnosis</h2>
      <p>
        AI output is for informational and wellness purposes only. It does not
        constitute a medical diagnosis, prescription, or treatment plan. Medication
        suggestions are educational and must be confirmed with a qualified doctor or
        pharmacist before use. For any concerning or worsening condition, consult a
        licensed clinician.
      </p>

      <h2>4. Risks &amp; limitations</h2>
      <p>
        AI predictions can be inaccurate or incomplete and may not detect every
        condition. Do not rely on ME as your sole source of health information.
      </p>

      <h2>5. Voluntary participation &amp; withdrawal</h2>
      <p>
        Providing consent is voluntary, but it is required to use the image-analysis
        features. You may withdraw consent at any time by contacting us or deleting
        your account; after withdrawal, no further analysis will be performed and your
        data will be deleted on request.
      </p>

      <h2>6. Contact</h2>
      <p>
        Consent or data questions? Email{' '}
        <a href="mailto:me.offical.team.system@gmail.com">me.offical.team.system@gmail.com</a>.
      </p>
    </StaticPage>
  );
}
