"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(@slwrk8pyqccvushh(-quuv%&jxtn00t7k71#w&wd^xz7z35$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# In production set: ALLOWED_HOSTS=yourapp.onrender.com,yourdomain.com
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # enables logout token invalidation
    'corsheaders',
    
    # Local apps
    'users',
    'image_analysis',
    'diagnosis',
    'recommendations',
    'feedback',
    'frontend',

    # Phase 2 apps
    'providers',
    'bookings',
    'makeup',
    'fashion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files in production
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be as high as possible
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Selection is controlled by the `USE_SQLITE` env flag:
#   USE_SQLITE=True  → local SQLite file (quick dev / offline testing)
#   USE_SQLITE=False → PostgreSQL (the real database, used for everything
#                      from auth onwards and in production)
# Keeping SQLite as an opt-in fallback means you can always switch back
# without editing code — just flip the flag in .env.
USE_SQLITE = os.getenv('USE_SQLITE', 'True') == 'True'

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'fyp_skin_scalp'),
            'USER': os.getenv('DB_USER', os.getenv('USER', 'postgres')),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# WhiteNoise compresses + caches static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Serve React production build static assets when running Django as a single server.
REACT_BUILD_STATIC_DIR = BASE_DIR / 'react' / 'build' / 'static'
STATICFILES_DIRS = [REACT_BUILD_STATIC_DIR] if REACT_BUILD_STATIC_DIR.exists() else []

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    # Local dev: long-lived tokens so you're never logged out mid-session.
    # Production: override via JWT_ACCESS_TOKEN_LIFETIME / JWT_REFRESH_TOKEN_LIFETIME env vars.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '480'))),   # 8 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '30'))),  # 30 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
# Add your Vercel production URL via env: CORS_ALLOWED_ORIGINS=https://yourapp.vercel.app
_extra_origins = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    *_extra_origins,
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Auth (session login for frontend)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Security Settings
# In production (DEBUG=False) all HTTPS and cookie flags are enabled automatically.
# In development they stay off so HTTP localhost still works.
IS_PRODUCTION = not DEBUG

SECURE_SSL_REDIRECT         = IS_PRODUCTION
SESSION_COOKIE_SECURE       = IS_PRODUCTION
CSRF_COOKIE_SECURE          = IS_PRODUCTION
SECURE_HSTS_SECONDS         = 31536000 if IS_PRODUCTION else 0   # 1 year HSTS in prod
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD         = IS_PRODUCTION
SECURE_BROWSER_XSS_FILTER  = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS             = 'DENY'

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Cache
# django_ratelimit requires a *shared* cache — the default LocMemCache is
# per-process and fails the system check. We use:
#   • FileBasedCache in local development (no extra services needed)
#   • Redis in production (set REDIS_URL env var on Render)
# Cache + Rate Limiting
# django_ratelimit requires Redis or Memcache (atomic increment support).
# In production set REDIS_URL and rate limiting is enforced.
# In local dev (no REDIS_URL) we use a dummy cache and disable rate limiting
# so the server starts without needing Redis installed locally.
_redis_url = os.getenv('REDIS_URL', '')
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
    INSTALLED_APPS += ['django_ratelimit']
    RATELIMIT_ENABLE = True
    RATELIMIT_USE_CACHE = 'default'
else:
    # No Redis: per-process LocMemCache. django_ratelimit's system check
    # raises E003 because LocMemCache isn't a shared cache — that's only
    # a concern when running multiple worker processes. For single-process
    # `runserver` (dev) it's fine, so we silence the check explicitly.
    # Production MUST set REDIS_URL to get a true shared cache.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'me-local-cache',
        }
    }
    INSTALLED_APPS += ['django_ratelimit']
    RATELIMIT_ENABLE = os.getenv('RATELIMIT_DISABLE', '0') != '1'
    RATELIMIT_USE_CACHE = 'default'
    SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# ── Ollama LLM configuration ────────────────────────────────────────
# Production must set OLLAMA_URL. Localhost is the dev default.
OLLAMA_URL    = os.getenv('OLLAMA_URL',   'http://localhost:11434')
OLLAMA_MODEL  = os.getenv('OLLAMA_MODEL', 'llama3.2')

# ── Groq LLM (PRIMARY recommendation engine for makeup/fashion) ──────
# Set GROQ_API_KEY in .env to enable. When empty, the code transparently
# falls back to the local Ollama model. Free key: https://console.groq.com
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL   = os.getenv('GROQ_MODEL', 'llama-3.3-70b-versatile')

# ── Email Settings ───────────────────────────────────────────────
# In development without EMAIL_HOST_USER set, emails print to the
# terminal. With EMAIL_HOST_USER + EMAIL_HOST_PASSWORD set, real SMTP
# (Gmail by default) sends actual messages.
#
# Gmail deliverability notes (so reset emails land in Primary inbox,
# not Spam):
#   1. From address MUST match the authenticated EMAIL_HOST_USER
#      (Gmail blocks "From: someone@otherdomain.com" spoofing).
#   2. We send multipart text + HTML, set Reply-To, and add
#      List-Unsubscribe + X-Auto-Response-Suppress headers — these
#      mark the message as transactional, which Gmail's classifier
#      uses to put it in Primary instead of Promotions/Spam.
#   3. Subject line is specific, not vague ("Reset your … password")
#      — vague subjects hurt deliverability.
_email_user = os.getenv('EMAIL_HOST_USER', '')
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', 'ME Skin Assistant')
if _email_user:
    EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST          = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT          = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS       = True
    EMAIL_HOST_USER     = _email_user
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_TIMEOUT       = 20   # don't hang the request forever
    # From address MUST be the authenticated Gmail address.
    DEFAULT_FROM_EMAIL  = f'{EMAIL_FROM_NAME} <{_email_user}>'
    SERVER_EMAIL        = _email_user
    EMAIL_SUBJECT_PREFIX = ''  # avoid "[Django] " prefix on error mails
else:
    # Console backend — emails print to the terminal during local dev.
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = f'{EMAIL_FROM_NAME} <noreply@fyp.local>'

# Frontend base URL used in password-reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# AI Model Settings
MEDIAPIPE_MODEL_PATH = os.getenv('MEDIAPIPE_MODEL_PATH', '')
UNET_MODEL_PATH = os.getenv('UNET_MODEL_PATH', '')

# Encryption Key for sensitive data
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', '').encode() if os.getenv('ENCRYPTION_KEY') else None

# Logging
# Replaces scattered `print()` debug calls. In DEBUG mode we show INFO-level
# logs from our own apps on the console; Django's noisy logs stay at WARNING.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Our own apps — keep at INFO (or DEBUG if DEBUG=True).
        'image_analysis': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
