#!/usr/bin/env python3
"""
Prepare eczema-only dataset with pseudo-masks generated by simple CV heuristics.

Output:
  data_eczema/
    images/   (copied image files)
    masks/    (generated binary PNG masks)

Then you can run the trainer on `data_eczema`.

This is a heuristic approach (no manual annotations). Masks will be noisy but
allow a quick smoke test of the segmentation training pipeline.
"""
from pathlib import Path
import cv2
import numpy as np
import argparse
import shutil


def generate_pseudo_mask(img: np.ndarray) -> np.ndarray:
    """Generate a binary mask for a skin lesion using simple heuristics.

    Steps:
    - Convert to gray, apply median blur
    - Apply contrast-limited adaptive histogram equalization (CLAHE)
    - Use Otsu thresholding to separate darker lesion from surrounding skin
    - Morphological opening and closing to clean noise
    - Keep largest connected component
    """
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 5)

    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    gray = clahe.apply(gray)

    # Otsu threshold
    _, th = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # Morphological cleaning
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    th = cv2.morphologyEx(th, cv2.MORPH_OPEN, kernel, iterations=1)
    th = cv2.morphologyEx(th, cv2.MORPH_CLOSE, kernel, iterations=2)

    # Keep largest connected component (if any)
    contours, _ = cv2.findContours(th.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return np.zeros_like(th)
    areas = [cv2.contourArea(c) for c in contours]
    max_idx = int(np.argmax(areas))
    mask = np.zeros_like(th)
    cv2.drawContours(mask, contours, max_idx, 255, -1)
    # Smooth edges
    mask = cv2.medianBlur(mask, 5)
    return mask


def prepare(eczema_dir: Path, out_dir: Path):
    eczema_dir = eczema_dir.resolve()
    out_dir = out_dir.resolve()
    imgs = sorted([p for p in eczema_dir.iterdir() if p.suffix.lower() in ('.jpg', '.jpeg', '.png')])
    print(f'Found {len(imgs)} eczema images in {eczema_dir}')

    images_out = out_dir / 'images'
    masks_out = out_dir / 'masks'
    images_out.mkdir(parents=True, exist_ok=True)
    masks_out.mkdir(parents=True, exist_ok=True)

    for i, p in enumerate(imgs):
        try:
            img = cv2.imread(str(p))
            if img is None:
                print('Warning: failed to read', p)
                continue
            mask = generate_pseudo_mask(img)

            dst_img = images_out / p.name
            dst_mask = masks_out / (p.stem + '.png')

            # Copy original image (trainer will resize)
            shutil.copy2(p, dst_img)

            # Save mask
            cv2.imwrite(str(dst_mask), mask)

            if (i + 1) % 200 == 0:
                print(f'Processed {i+1}/{len(imgs)}')
        except Exception as e:
            print('Error processing', p, e)

    print('Prepared dataset at', out_dir)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--eczema_folder', type=str, default='dataset/skin_dataset/IMG_CLASSES/1. Eczema 1677')
    parser.add_argument('--out', type=str, default='data_eczema')
    args = parser.parse_args()

    prepare(Path(args.eczema_folder), Path(args.out))
