# Generated by Django 4.2.7 on 2026-04-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_condition', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity_level', models.CharField(default='Mild', max_length=20)),
                ('all_conditions', models.JSONField(default=list)),
                ('recommend_dermatologist', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='image_analysis.analysisresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
